version: '3.8'

services:
  app:
    build: .
    ports:
      - 25000:25000
    environment:
      - DB_USER=db_user
      - DB_PASSWORD=db_password
      - DB_NAME=db_name
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    ports:
      - 5436:5432
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 1s
      timeout: 10s
      retries: 120
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name
